In [8]:
my_list = [1,2,3]

In [2]:
import numpy as np

In [7]:
arr = np.array(my_list)

In [4]:
arr

array([1, 2, 3])

In [9]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [10]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.arange(0,11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [13]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [14]:
np.zeroes(3)

AttributeError: module 'numpy' has no attribute 'zeroes'

In [15]:
np.zeros(3)

array([0., 0., 0.])

In [16]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [17]:
np.ones(3)

array([1., 1., 1.])

In [18]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [19]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [20]:
np.linspace(0,5,100)

array([0.        , 0.05050505, 0.1010101 , 0.15151515, 0.2020202 ,
       0.25252525, 0.3030303 , 0.35353535, 0.4040404 , 0.45454545,
       0.50505051, 0.55555556, 0.60606061, 0.65656566, 0.70707071,
       0.75757576, 0.80808081, 0.85858586, 0.90909091, 0.95959596,
       1.01010101, 1.06060606, 1.11111111, 1.16161616, 1.21212121,
       1.26262626, 1.31313131, 1.36363636, 1.41414141, 1.46464646,
       1.51515152, 1.56565657, 1.61616162, 1.66666667, 1.71717172,
       1.76767677, 1.81818182, 1.86868687, 1.91919192, 1.96969697,
       2.02020202, 2.07070707, 2.12121212, 2.17171717, 2.22222222,
       2.27272727, 2.32323232, 2.37373737, 2.42424242, 2.47474747,
       2.52525253, 2.57575758, 2.62626263, 2.67676768, 2.72727273,
       2.77777778, 2.82828283, 2.87878788, 2.92929293, 2.97979798,
       3.03030303, 3.08080808, 3.13131313, 3.18181818, 3.23232323,
       3.28282828, 3.33333333, 3.38383838, 3.43434343, 3.48484848,
       3.53535354, 3.58585859, 3.63636364, 3.68686869, 3.73737

In [21]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [22]:
np.random.rand(5)

array([0.43126533, 0.80892335, 0.74808904, 0.08796649, 0.13946161])

In [23]:
np.random.rand(4,4)

array([[5.31534895e-01, 3.19453291e-01, 4.27066550e-01, 2.95519217e-01],
       [3.11482223e-01, 8.57831687e-01, 1.04145887e-04, 4.70545766e-01],
       [9.88529968e-01, 5.12458495e-01, 9.40313643e-01, 9.13048680e-01],
       [2.90932702e-01, 6.05511586e-01, 2.73245056e-01, 2.02799698e-01]])

In [24]:
np.random.randn()

-0.366412563167971

In [25]:
np.random.randn(2)

array([ 0.31257592, -0.67453712])

In [26]:
np.random.randn(2,2)

array([[-0.86654072,  0.89379578],
       [ 0.03019016,  0.669582  ]])

In [27]:
np.random.randint(1,100)

32

In [28]:
np.random.randint(1,100,10)

array([74, 32, 15,  1, 43, 22, 77, 50, 42, 97])

In [29]:
arr = np.arange(25)

In [30]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [31]:
ranarr = np.random.randint(0,50,10)

In [32]:
ranarr

array([14, 40, 42, 26, 25, 36,  0, 10, 29, 10])

In [33]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [34]:
arr.reshape(5,10)

ValueError: cannot reshape array of size 25 into shape (5,10)

In [36]:
ranarr.max()

42

In [37]:
ranarr.min()

0

In [38]:
ranarr.argmax()

2

In [39]:
ranarr.min()

0

In [40]:
ranarr.argmin()

6

In [41]:
arr.shape

(25,)

In [42]:
r=arr.reshape(5,5)

In [43]:
r

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [44]:
arr.dtype

dtype('int32')

In [45]:
from numpy.random import randint

In [46]:
randint(2,10)

2